Repository nethanel-ctrl/Localdb, pull requests merged in 2024-12, with the labels that each got.

#1 :rescue_worker_helmet: "added github actions for bun"
  .github/workflows/ci.yaml
Labels: enhancement

#7 :paperclip: "modified readme"
  README.md
Labels: documentation

#9 :package: "updated typescript and prettier"
  package.json
Labels: bug
